/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AsistenRouteImport } from './routes/asisten'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as PelacakanRouteImport } from './routes/pelacakan'
import { Route as PengaduanRouteImport } from './routes/pengaduan'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalitikRouteImport } from './routes/admin/analitik'
import { Route as AdminKnowledgeRouteImport } from './routes/admin/knowledge'
import { Route as AdminLayananRouteImport } from './routes/admin/layanan'
import { Route as AdminPengaduanRouteImport } from './routes/admin/pengaduan'
import { Route as LayananPengajuanRouteImport } from './routes/layanan_.pengajuan'
import { Route as PengaduanBaruRouteImport } from './routes/pengaduan_.baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenRoute = AsistenRouteImport.update({
  id: '/asisten',
  path: '/asisten',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const PelacakanRoute = PelacakanRouteImport.update({
  id: '/pelacakan',
  path: '/pelacakan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanRoute = PengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalitikRoute = AdminAnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayananRoute = AdminLayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaduanRoute = AdminPengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => AdminRoute,
} as any)
const LayananPengajuanRoute = LayananPengajuanRouteImport.update({
  id: '/layanan_/pengajuan',
  path: '/layanan/pengajuan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanBaruRoute = PengaduanBaruRouteImport.update({
  id: '/pengaduan_/baru',
  path: '/pengaduan/baru',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/asisten': typeof AsistenRoute
  '/layanan': typeof LayananRoute
  '/pelacakan': typeof PelacakanRoute
  '/pengaduan': typeof PengaduanRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/layanan/pengajuan': typeof LayananPengajuanRoute
  '/pengaduan/baru': typeof PengaduanBaruRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asisten': typeof AsistenRoute
  '/layanan': typeof LayananRoute
  '/pelacakan': typeof PelacakanRoute
  '/pengaduan': typeof PengaduanRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/layanan/pengajuan': typeof LayananPengajuanRoute
  '/pengaduan/baru': typeof PengaduanBaruRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/asisten': typeof AsistenRoute
  '/layanan': typeof LayananRoute
  '/pelacakan': typeof PelacakanRoute
  '/pengaduan': typeof PengaduanRoute
  '/admin/analitik': typeof AdminAnalitikRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/layanan': typeof AdminLayananRoute
  '/admin/pengaduan': typeof AdminPengaduanRoute
  '/layanan_/pengajuan': typeof LayananPengajuanRoute
  '/pengaduan_/baru': typeof PengaduanBaruRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/asisten'
    | '/layanan'
    | '/pelacakan'
    | '/pengaduan'
    | '/admin/analitik'
    | '/admin/knowledge'
    | '/admin/layanan'
    | '/admin/pengaduan'
    | '/layanan/pengajuan'
    | '/pengaduan/baru'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asisten'
    | '/layanan'
    | '/pelacakan'
    | '/pengaduan'
    | '/admin/analitik'
    | '/admin/knowledge'
    | '/admin/layanan'
    | '/admin/pengaduan'
    | '/layanan/pengajuan'
    | '/pengaduan/baru'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/asisten'
    | '/layanan'
    | '/pelacakan'
    | '/pengaduan'
    | '/admin/analitik'
    | '/admin/knowledge'
    | '/admin/layanan'
    | '/admin/pengaduan'
    | '/layanan_/pengajuan'
    | '/pengaduan_/baru'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AsistenRoute: typeof AsistenRoute
  LayananRoute: typeof LayananRoute
  PelacakanRoute: typeof PelacakanRoute
  PengaduanRoute: typeof PengaduanRoute
  LayananPengajuanRoute: typeof LayananPengajuanRoute
  PengaduanBaruRoute: typeof PengaduanBaruRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asisten': {
      id: '/asisten'
      path: '/asisten'
      fullPath: '/asisten'
      preLoaderRoute: typeof AsistenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelacakan': {
      id: '/pelacakan'
      path: '/pelacakan'
      fullPath: '/pelacakan'
      preLoaderRoute: typeof PelacakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan': {
      id: '/pengaduan'
      path: '/pengaduan'
      fullPath: '/pengaduan'
      preLoaderRoute: typeof PengaduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analitik': {
      id: '/admin/analitik'
      path: '/analitik'
      fullPath: '/admin/analitik'
      preLoaderRoute: typeof AdminAnalitikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/layanan': {
      id: '/admin/layanan'
      path: '/layanan'
      fullPath: '/admin/layanan'
      preLoaderRoute: typeof AdminLayananRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaduan': {
      id: '/admin/pengaduan'
      path: '/pengaduan'
      fullPath: '/admin/pengaduan'
      preLoaderRoute: typeof AdminPengaduanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/layanan_/pengajuan': {
      id: '/layanan_/pengajuan'
      path: '/layanan/pengajuan'
      fullPath: '/layanan/pengajuan'
      preLoaderRoute: typeof LayananPengajuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan_/baru': {
      id: '/pengaduan_/baru'
      path: '/pengaduan/baru'
      fullPath: '/pengaduan/baru'
      preLoaderRoute: typeof PengaduanBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalitikRoute: typeof AdminAnalitikRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminLayananRoute: typeof AdminLayananRoute
  AdminPengaduanRoute: typeof AdminPengaduanRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalitikRoute: AdminAnalitikRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminLayananRoute: AdminLayananRoute,
  AdminPengaduanRoute: AdminPengaduanRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AsistenRoute: AsistenRoute,
  LayananRoute: LayananRoute,
  PelacakanRoute: PelacakanRoute,
  PengaduanRoute: PengaduanRoute,
  LayananPengajuanRoute: LayananPengajuanRoute,
  PengaduanBaruRoute: PengaduanBaruRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
